AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  Author: Antonella Mira
  Description: Plantilla para la creación de una API REST
  Version: '1.0'
Parameters:
  pNameProject:
    Description: Parameter with the name of the project
    Type: String
    MinLength: 3
    MaxLength: 15
    Default: NameProjectDef
Resources:
  ApiRestGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: first-api-cloudformation
      Description: API creada con cloudformation
      Body:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: s3://antonella-course-us-east-1/544f0c0e3895fc4133121dcc94b2724e
  DeploymentApiRest:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: Etapa de desarrollo
      RestApiId:
        Ref: ApiRestGateway
      StageName: development
  RoleFunctionLambda:
    Type: AWS::IAM::Role
    Properties:
      RoleName: role-lambda-api
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  LambdaFunctionAPI:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
      - x86_64
      Code:
        ZipFile: "import os\ndef handler(event, context):\n  return {\"message\":\
          \ \"Hello world with API Gateway and Lambda\", \"environment\": os.environ.get(\"\
          PROJECT\")}\n"
      Description: Esta lambda devuelve un hola mundo y la variable de entorno
      Environment:
        Variables:
          PROJECT:
            Ref: pNameProject
      EphemeralStorage:
        Size: 512
      FunctionName: lambda-apigateway-code-template
      Handler: index.handler
      MemorySize: 128
      PackageType: Zip
      RecursiveLoop: Terminate
      Role:
        Fn::GetAtt:
        - RoleFunctionLambda
        - Arn
      Runtime: python3.13
      Tags:
      - Key: Project
        Value: Udemy course of AWS Development serverless
      Timeout: 60
  LambdaPermissionApiGateway:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: LambdaFunctionAPI
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:execute-api:us-east-1:${AWS::AccountId}:${ApiRestGateway}/*/*/*
