AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  Author: Antonella Mira
  Description: Plantilla básica con S3
  Version: '1.0'
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        !Sub "antonella-course-${AWS::Region}"
# son datos informativos, sirven de referencia
Outputs:
  MyBucketName:
    Description: "Nombre final del bucket s3 después de reemplazos"
    Value: !Ref MyBucket